[package]
name = "wow-addon-manager"
version = "0.1.0"
authors = ["Hilmar Wiegand <me@hwgnd.de>"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.9.2"
zip = "0.4"
select = "0.4"
